# Generated by Django 3.2.20 on 2023-11-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Entre com o título:', max_length=100)),
                ('texto', models.CharField(help_text='Digite o texto da publicação:', max_length=10000)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(help_text='Digite o comentário:', max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPublicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.publicacao')),
            ],
        ),
    ]
